// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDUMJsZx0fmhVQxHTjtreM4WNy1Y1k2Ps',
    appId: '1:763181036602:web:27d463b873c3fa35ef7103',
    messagingSenderId: '763181036602',
    projectId: 'fir-todo-cb70e',
    authDomain: 'fir-todo-cb70e.firebaseapp.com',
    storageBucket: 'fir-todo-cb70e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF9mGxpZ1So3UvYZhwRnV92bR0NcCOL6k',
    appId: '1:763181036602:android:43f933c4ddd7e88aef7103',
    messagingSenderId: '763181036602',
    projectId: 'fir-todo-cb70e',
    storageBucket: 'fir-todo-cb70e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDUMJsZx0fmhVQxHTjtreM4WNy1Y1k2Ps',
    appId: '1:763181036602:web:9a57859f5e5d3593ef7103',
    messagingSenderId: '763181036602',
    projectId: 'fir-todo-cb70e',
    authDomain: 'fir-todo-cb70e.firebaseapp.com',
    storageBucket: 'fir-todo-cb70e.appspot.com',
  );
}
